drop database if exists customer_behavior;
create database customer_behavior;

use customer_behavior;

select * from customer;

select count(`customer ID`)
from customer;

-- Q1. What is the total revenue generated by male vs. female customers?
select `gender`, sum(`purchase amount (USD)`) as total_revenue
FROM customer
group by `gender`;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select `customer id`, `purchase amount (USD)`
from customer
where `discount applied` = 'yes' and 
	`purchase amount (USD)` >= (select avg(`purchase amount (USD)`) from customer);
    
-- Q3. Which are the top 5 products with the highest average review rating?
select `item purchased`, round(avg(`review rating`;:numeric),2) as "Average_product_rating"
from customer
group by `item purchased`
order by avg(`review rating`) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select `shipping type`,
	round(avg(`purchase amount (USD)`),2)
from customer
where `shipping type` in ('Standard', 'Express')
group by `shipping type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select `subscription status`,
		count(`customer id`) as total_customer,
        avg(`purchase amount (USD)`) as avg_spend,
        sum(`purchase amount (USD)`) as total_revenue
from customer
group by `subscription status`
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select * from customer;

SELECT `item purchased`,
       ROUND(100.0 * SUM(CASE WHEN `discount applied` = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY `item purchased`
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with `customer type` as (
SELECT `customer id`, `previous purchases`,
CASE 
    WHEN `previous purchases` = 1 THEN 'New'
    WHEN `previous purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS `customer segment`
FROM customer)

select `customer segment`,count(*) AS "Number of Customers" 
from `customer type` 
group by `customer segment`;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           `item purchased`,
           COUNT(`customer id`) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(`customer id`) DESC) AS item_rank
    FROM customer
    GROUP BY category, `item purchased` 
)
SELECT item_rank,`category`, `item purchased`, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `subscription status`,
       COUNT(`customer id`) AS repeat_buyers
FROM customer
WHERE `previous purchases` > 5
GROUP BY `subscription status`;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(`purchase amount (USD)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;